name: CI/CD Webserver

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Build da imagem Docker
        run: |
          docker build -t ragazzikyndryl/webserver:latest .

      - name: Push para Docker Hub
        run: |
          echo ${{ secrets.malarial7abe4furnish.dregs}} | docker login -u ${{ secrets.ragazzikyndryl }} --password-stdin
          docker push gragazzi/webserver:latest

      - name: Deploy no Kubernetes
        run: |
          kubectl apply -f k8s-deployment.yaml
          kubectl set image deployment/webserver webserver=ragazzikyndryl/webserver:latest
          kubectl rollout status deployment/webserver
